### ISSUE TITLE
compartment_ocid variable declared but not used for creation of FoggyKitchenCompartment compartment

### ISSUE THREAD

**Issue by aorcl** [mlinxfeld/foggykitchen_tf_oci_course#1]
Hello, Martin, I've pinged you on linkedin couple of days ago ;) 

Doing a workshop using your examples, I've had to modify all the compartment.tf files to make them to create the "FoggyKitchenCompartment" not in root but inside a compartment that was set up in the input variables. In many workshop situations users don't have rights to create resources in root, also using an already existing variable makes sense.

I'll assign this issue to myself and push you a corresponding PR in due time (couple of days maybe).

Regards

**Comment by aorcl** [comment]
Ok, no right to assign it to myself (obviously - facepalm)

**Comment by mlinxfeld** [comment]
I have added you to the collab team here. I am planning to fix it within the next 24-48 hours. COVID-19 has introduced a lot of mess in my life :)

**Comment by aorcl** [comment]
Thanks!

**Comment by mlinxfeld** [comment]
Fixed :) in each lesson check compartment.tf file:

`
resource "oci_identity_compartment" "FoggyKitchenCompartment" {
  name = "FoggyKitchenCompartment"
  description = "FoggyKitchen Compartment"
  compartment_id = var.compartment_ocid
}
`

**Comment by aorcl** [comment]
Doh you're too fast!

I've spent too much time rebasing my stuff ;) 
Thanks anyway

**Comment by mlinxfeld** [comment]
Don't leave it for tomorrow what you can do today!

**Comment by mlinxfeld** [comment]
https://foggykitchen.com/2020/03/19/oci-subcompartments-support-in-terraform/
