### ISSUE TITLE
replace hard coded Availability domains by dynamicly retrieved

### ISSUE THREAD

**Issue by aorcl** [mlinxfeld/foggykitchen_tf_oci_course#2]
The ADs are hardcoded in variables.tf and these are always tenancy and region-specific.
Need to retrieve the ADs dynamically using data sources to avoid manual changes.

**Comment by mlinxfeld** [comment]
I have updated it recently. Current commit contains the fixes implemented in many terraform files:

**variables.tf**
`
(...)
#variable "ADs" {
#  default = ["unja:EU-FRANKFURT-1-AD-1", "unja:EU-FRANKFURT-1-AD-2", "unja:EU-FRANKFURT-1-AD-3"]
#}

(...)
variable "OsImage" {
  # Oracle-Linux-7.7-2020.02.21-0 in Frankfurt
  default = "Oracle-Linux-7.7-2020.02.21-0"
}

#variable "Images" {
 # Oracle-Linux-7.7-2019.11.12-0 in Frankfurt
# default = ["ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa3bu75jht762mfvwroa2gdck6boqwyktztyu5dfhftcycucyp63ma"]
#}
`

**VCN.tf**
`
(...)
# Gets a list of Availability Domains
data "oci_identity_availability_domains" "ADs" {
  compartment_id = var.tenancy_ocid
}

# Gets the Id of a specific OS Images
data "oci_core_images" "OSImageLocal" {
  #Required
  compartment_id = var.compartment_ocid
  display_name   = var.OsImage
}`

**webserver1.tf**
`resource "oci_core_instance" "FoggyKitchenWebserver1" {
  availability_domain = lookup(data.oci_identity_availability_domains.ADs.availability_domains[1], "name")
  compartment_id = oci_identity_compartment.FoggyKitchenCompartment.id
  display_name = "FoggyKitchenWebServer1"
  shape = var.Shapes[0]
  subnet_id = oci_core_subnet.FoggyKitchenWebSubnet.id
  source_details {
    source_type = "image"
    source_id   = lookup(data.oci_core_images.OSImageLocal.images[0], "id")
  }
(...)
`

**Comment by aorcl** [comment]
Sure, let me sync that back to my fork
